name: SurvivalSystem
version: 1.0
authors: [Aaron alias TheSaltyOne, Patrick]
main: me.aaron.survivalsystem.main.Main
depend: [WorldEdit, WorldGuard]
api-version: 1.13

commands:
  setup:
    description: Does the setup mode
    permission: survivalsystem.setup 
  rtp:
    description: LOL
  checkarray:
    description: DEV COMMAND DONT TOUCH
  checkareas:
    description: DEV COMMAND DONT TOUCH

permissions:
  survivalsystem.setup:
    description: Allows the setup command